### ISSUE TITLE
Feat: 종류별 알림 기능 추가

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#101]
## 📌 Feature Issue
종류별 알림 기능을 구현합니다.

## 📝 To-do
- [x] handleNotificationEvent 로직 수정
    - 필드 알림일 경우 하나의 알림만 저장
---
- 알림 적용 대상 API - 대상 (유저 알림 OR  필드 알림)
    - [x] **DELETE [/user-field/{id}/eject]** 팀원 내보내기
        - 상대방(유저 알림) - [팀 이름] 에서 퇴출되었습니다.
        - 내 필드(필드 알림)  - [팀 이름] 에서 [팀원]을 내보냈습니다.
    - [x] **DELETE [/user-field/{id}/exit]** 필드 나가기 필드
        - 해당 필드 (필드 알림) - [팀원]이 [팀 이름]을 나갔습니다.
    - [x] **POST [/user-field/alert/{id}]** 팀원 깨우기
        - 필드 팀원 모두 (유저 알림)
    - [x] **POST [/user-field/cheer/{id}]** 응원하기
        - 타겟 유저 (유저 알림)

    - [x] **PATCH [/field/{id}/change-leader]** 방장 넘기기
        - 해당 필드 (필드 알림) - [방장]이 [팀 이름]의 방장이 되었습니다.
    - [x] **PATCH [/field/{id}/info]** 필드 정보 수정, **POST [/field/{id}/profile]** 필드 프로필 수정
        - 해당 필드 (필드알림) - [팀 이름]의 정보가 수정되었습니다.
    - [x] **POST [/field-entry/{id}/accept]** 필드 수락
        - 1대1, 팀 배틀
            - 양 측 필드 (필드 알림) - 배틀이 성사되었습니다.
        - 팀원
            - (필드 알림) - [팀원]이 입장했습니다.
            - (유저 알림) - [팀 이름]에 소속되었습니다.
 
## ETC
>
