### ISSUE TITLE
Init: 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#2]
## 📌 Feature Issue
프로젝트 초기 세팅

## 📝 To-do
- [x] Branch Rule 설정
- [x] .gitignore 설정
- [x] Readme 초안 작성
- [x] 패키지 구조 분리
- [x] Swagger 설정
- [x] QueryDsl 설정
