### ISSUE TITLE
Infra: 인프라 초기 세팅

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#3]
## 📌 Feature Issue
- AWS - EC2, RDS, S3
- CI/CD - Github Actions, CodeDeploy
- ETC - Nginx, Redis

## 📝 To-do
- [x] 프로젝트 아키텍처 설계
- [x] AWS 계정 생성
- [x] EC2 세팅
- [x] RDS 세팅
- [x] S3 세팅
- [x] Nginx 세팅
- [x] CI/CD 세팅
