### ISSUE TITLE
Feat: Exercise API 구현

### ISSUE THREAD

**Issue by kaley0421** [dnd-side-project/dnd-9th-9-backend#42]
## 📌 Feature Issue
- 운동 기록 관련 API 를 구현합니다.

## 📝 To-do
- [x] 매치업 내 운동기록 조회/등록/수정/삭제 API
- [x] 애플 데이터 등록 API
- [x] 운동 즐겨찾기 조회/등록/삭제 API
- [x] 애플 활동링 정보 등록 API
- [x] 날짜 별 칼로리 정보 불러오기 API
---
- [x] 오늘 나의 기록 요약 API
- [x] 최근 많이 한 운동 불러오기 API
- [x] S3 이미지 업로드

## ETC
>
