### ISSUE TITLE
Feat: FieldController 리팩터링 및 오류수정

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#44]
## 📌 Feature Issue
FIeldController의 오류를 수정하고 리팩터링합니다.

## 📝 To-do
- [x] RequestBody -> ModelAttribute
- [x] createField 로직 추가
- [x] 기록 API 로직 수정
- [x] 리팩터링
- [x] Swagger 설명 추가 

## ETC
>
