### ISSUE TITLE
Feat: 매치 시작, 종료 스케줄러, 종료 관련 API 구현

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#49]
## 📌 Feature Issue
매치 시작, 종료 스케줄러와 매치 종료 관련 API를 구현합니다.

## 📝 To-do
- [ ] 매치 시작 스케줄러
- [ ] 매치 종료 스케줄러
- [ ] 매치 종료 정보 불러오기

## ETC
>
