### ISSUE TITLE
검색 기능 추가 및 필드 관련 API 수정

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#60]
## 📌 Feature Issue
검색 기능 추가 및 필드 관련 API를 수정합니다.

## 📝 To-do
- [x] 필드 검색 API에 검색 기능 추가
- [x] 단일 필드 조회 - RequestDto <팀 상태, 권한 상태> 필드값 추가
- [x] 종료된 매치 조회 응답 값 추가
- [x] Validation 및 Swagger 수정

## ETC
>
