### ISSUE TITLE
Fix: 프론트와의 조율에 따른 변경

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#67]
## 📌 Feature Issue
프론트엔드 측과의 요청/응답 형식 조율에 따른 수정사항을 적용합니다.

## 📝 To-do
- [x] findAllFields 조건 변경
    - 빈 리스트일 경우 모두 조회
- [x] Pagination 사용 API 응답값 추가
    - currentPageSize
    - currentPageNumber
- [x] Swagger 응답값 코드 추가

## ETC
>
