### ISSUE TITLE
Feat: User API 구현

### ISSUE THREAD

**Issue by kaley0421** [dnd-side-project/dnd-9th-9-backend#68]
## 📌 Feature Issue
- UserController 의 API 들을 구현합니다.

## 📝 To-do
- [x] 내 정보 상세 조회
- [x] 온보딩 시 내 정보 업데이트
- [x] 온보딩 시 운동레벨 등록
- [x] 내 프로필 수정
- [x] 애플 연동 여부 수정
- [x] 알림 수신 여부 수정

## ETC
>
