### ISSUE TITLE
Fix: 필드 신청 내역 삭제, 수락 및 팀원 내보내기 로직 수정

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#80]
## ⚙️ 발생 기능
- FieldEntry
    - deleteFieldEntry
    - acceptFieldEntry
- UserField
    - ejectMember

## ❓ 발생 상황
- 팀원 내보내기 시 방장이 본인을 내보낼 수 있는 문제
- 필드 신청 내역 삭제 시 권한 문제
- 필드 신청 수락에 따른 삭제 로직 추가

## 📝 To-do
- [x] deleteFieldEntry 예외 처리 추가
- [x] ejectEntry 권한 로직 수정
- [x] acceptFieldEntry 수락에 따른 삭제 로직 추가

## ETC
>
