### ISSUE TITLE
Fix: 매칭 시작 시점 정책 통일 및 배틀 보유 여부 확인 API 추가, 에러 메시지 변경

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#85]
## 📌 Feature Issue
매칭 시작 시점에 따른 화면 노출 정책을 통일합니다.

## 📝 To-do
- [x] 필드 단일 조회 - 상대편 데이터 추가 조건 변경
    - `fieldStauts == IN_PRORRESS` -> `assignedFieldDto == null `

- [x] 배틀 보유 여부 확인 API 추가 - checkOwnBattle

- [x] Patch, Delete 메서드 - 에러 메시지 정책 변경으로 인한 수정 (앱에 그대로 노출)
    - Delete, Patch 메서드 에러 메시지 피그마와 통일
        - 팀을 나가기 위해서는\n다른 팀원에게 방장을 넘겨야 해요.
        - ”알 수 없는 오류가 발생하였습니다.”, “잘못된 요청입니다.*\n*다시 한 번 확인해주세요” 로 에러 메시지 변경

- [x] MultipartFile Post 메서드로 변경

## ETC
>
