### ISSUE TITLE
Feat: 나의 매칭 조회 API, 자동 매칭 중복 방지 로직 추가 및 매칭 결과 API 수정

### ISSUE THREAD

**Issue by Ju-yeop** [dnd-side-project/dnd-9th-9-backend#92]
## 📌 Feature Issue
매칭관련 API 추가 및 수정

## 📝 To-do
- 매칭 결과 API
    - [x] 점수 -> 이긴 횟수 카운트
    - [x] 시작일, 종료일
- [x] 나의 매칭 조회 API 추가
- [x] 자동 매칭 중복 방지 로직 추가

## ETC
>
